Vagrant.configure(2) do |config|

  config.vm.define "openbsddummy" do |od|
    od.vm.box = "ryanmaclean/openbsd-6.0"
    od.vm.hostname = "openbsddummy"
    od.vm.network "private_network", ip: "192.168.12.42"

    od.vm.provider "virtualbox" do |vb|
      vb.name = "elastic_elks_openbsddummy"
      vb.cpus = 1
      vb.memory = 512
    end

    od.vm.provision "shell", inline: <<-SHELL
      sudo echo 'installpath = https://ftp.spline.de/pub/OpenBSD/6.0/packages/amd64/' > /etc/pkg.conf
      sudo echo 'export PKG_PATH=https://ftp.spline.de/pub/OpenBSD/6.0/packages/amd64/' >> ~/.profile
      sudo pkg_add python-2.7.12
      sudo ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
      sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python
      sudo ln -sf /usr/local/bin/python2.7-2to3 /usr/local/bin/2to3
      sudo ln -sf /usr/local/bin/python2.7-config /usr/local/bin/python-config
      sudo ln -sf /usr/local/bin/pydoc2.7  /usr/local/bin/pydoc
     SHELL

    od.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.groups = {
        "syslog-openbsd"  => ["openbsddummy"]
      }
      ansible.host_vars = {
        "openbsddummy" => {
          "elastic_backend_ip" => "192.168.12.40"
        }
      }
    end
  end

  config.vm.define "debiandummy" do |dd|
    dd.vm.box = "debian/jessie64"
    dd.vm.hostname = "debiandummy"
    dd.vm.network "private_network", ip: "192.168.12.41"

    dd.vm.provider "virtualbox" do |vb|
      vb.name = "elastic_elks_debiandummy"
      vb.cpus = 1
      vb.memory = 512
    end

    dd.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.groups = {
        "rsyslog-debian"  => ["debiandummy"]
      }
      ansible.host_vars = {
        "debiandummy" => {
          "elastic_backend_ip" => "192.168.12.40"
        }
      }
    end
  end

  config.vm.define "elkstest" do |et|
    et.vm.box = "debian/jessie64"
    et.vm.hostname = "elkstest"
    et.vm.network "private_network", ip: "192.168.12.40"

    et.vm.provider "virtualbox" do |vb|
      vb.name = "elastic_elks_elkstest"
      vb.cpus = 2
      vb.memory = 4096
    end

    et.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.groups = {
        "elks" => ["elkstest"],
      }
      ansible.host_vars = {
        "elkstest" => {
          "elastic_backend_ip" => "192.168.12.40",
          "kibana_ip" => "0.0.0.0"
        }
      }
    end
  end
end
