Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.define "elkstest" do |elkstest|
    elkstest.vm.hostname = "elkstest"
    elkstest.vm.network "private_network", ip: "192.168.12.40"

    elkstest.vm.provider "virtualbox" do |vb|
      vb.name = "elastic_elks_elkstest"
      vb.cpus = 2
      vb.memory = 4096
    end

    elkstest.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.host_vars = {
        "elkstest" => {
          "elastic_backend_ip" => "127.0.0.1",
          "kibana_ip" => "0.0.0.0"
        }
      }
    end
  end
end
