---
- hosts: all
  tasks:
     - group_by: key=os_{{ ansible_distribution }}

- hosts: elks
  gather_facts: False
  roles:
    - role: ntp-debian
    - role: elastic-backend
    - role: rsyslog-debian
    - role: kibana

- hosts: rsyslog-debian
  gather_facts: False
  roles:
    - role: ntp-debian
    - role: rsyslog-debian

- hosts: syslog-openbsd
  gather_facts: False
  roles:
    - role: timezone
    - role: syslog-openbsd
