- name: Install new rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  become: true
  notify:
    - restart rsyslog

- name: Install new rsyslog template file
  template:
    src: 01-json-template.conf.j2
    dest: /etc/rsyslog.d/01-json-template.conf
  become: true
  notify:
    - restart rsyslog

- name: Install new rsyslog output configuration file
  template:
    src: 60-output.conf.j2
    dest: /etc/rsyslog.d/60-output.conf
  become: true
  notify:
    - restart rsyslog

- name: Make sure rsyslog is enabled.
  systemd:
    name: rsyslog
    enabled: yes
    state: started
  become: true
