- name: Install Kibana
  apt:
    name: kibana
    state: latest
  become: true

- name: Install new Kibana configuration file
  template:
    src: ./kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  become: true

- name: Enable and restart the Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: restarted
  become: true
